### ISSUE TITLE
Passing arguments to tasks?

### ISSUE THREAD

**Issue by pmav99** [illBeRoy/taskipy#1]
Is it possible to pass arguments to tasks?

**Comment by illBeRoy** [comment]
Hey!
It is not possible yet. I’ll look into adding it, and keep you updated in the following days :)

**Comment by pmav99** [comment]
Thank you for the prompt reply

**Comment by illBeRoy** [comment]
Hey again! I've created an enhancement pull request [here](https://github.com/illBeRoy/taskipy/pull/2). Once it passes CI checks, I will merge and publish the new version.

**Comment by illBeRoy** [comment]
feature added in v1.1.0
