### ISSUE TITLE
Backport and use a changelog

### ISSUE THREAD

**Issue by eugenetriguba** [illBeRoy/taskipy#16]
It would be nice if the project had some sort of changelog so users of the package would know what is changing with each release and, if the package has a major version bump, what breaking changes may have occurred. 

For ideas, I like the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format personally.

**Comment by eugenetriguba** [comment]
I had originally opened this issue in 2020. I would be open to doing the backport work, but I do still think that a changelog would be a great addition. As more and more releases go by, I don't think we want to force users of the package to have to follow the development and read the source code changes of the commits to get a feel for what has changed.

**Comment by Granitosaurus** [comment]
<3 Change logs! 
Though I'm not sure if it's worth backporting everything.

**Comment by eugenetriguba** [comment]
@Granitosaurus Agreed, it may be overkill. I just like having the full history. But the general request of using a changelog would be nice to have as an end user :smile:
