### ISSUE TITLE
could not find task "None"

### ISSUE THREAD

**Issue by tueda** [illBeRoy/taskipy#30]
If no argument is given, then taskipy gives the following error message:
```sh
$ poetry run task
could not find task "None"
```
This might be a bit improved as "no task given" or taskipy could print the help or list of available tasks (though I think the exit code `127` is fine and indeed should be kept).

**Comment by illBeRoy** [comment]
Hi @tueda, thanks for the feedback!
You are indeed correct and this could be improved.
I'll see if I can get to it during the next couple of days. Nonetheless, if you want you are more than welcome to open a PR!

**Comment by illBeRoy** [comment]
Hello! Thanks to @eugenetriguba , a fix was merged and released with taskipy 1.7.0.
Please confirm that the issue was fixed for you, and I'll mark this issue as resolved

**Comment by tueda** [comment]
Thank you! I have confirmed taskipy 1.7.0 nicely works.

**Comment by illBeRoy** [comment]
glad to hear! closing
