### ISSUE TITLE
Recursive variables aren't resolved when listing tasks

### ISSUE THREAD

**Issue by eugenetriguba** [illBeRoy/taskipy#49]
I noticed that when listing out the tasks, the tasks are shown as-is, without resolving the variables to display their actual value.

For instance,
```
$ task --list
test         task test_unit
test_unit    pytest {unit_test_dir} -v --cov {src_dir} --cov-report term-missing
test_ci      task test_unit --cov-report xml --junitxml=report.xml
lint         task lint_format && task lint_analyze && task lint_types
lint_analyze flake8 {module_dir} {tests_dir}
lint_format  black {module_dir} {tests_dir} && isort {module_dir} {tests_dir}
lint_types   mypy {module_dir} {tests_dir}
```

But I would expect

```
$ task --list
test         task test_unit
test_unit    pytest tests/unit -v --cov src --cov-report term-missing
test_ci      task test_unit --cov-report xml --junitxml=report.xml
lint         task lint_format && task lint_analyze && task lint_types
lint_analyze flake8 some_module tests
lint_format  black some_module tests && isort some_module tests
lint_types   mypy some_module tests
```

Happy to tackle this if deemed desirable. I would think when listing the tasks, we would want to see the values of those variables.

**Comment by eugenetriguba** [comment]
Hey! Apologies for the delayed response.

Instead of having a configuration option and substituting in the variables into the tasks themselves, would it make more sense to list the variables and their values out at the end instead?

(not final and would be interested in any ideas you have here but something along the lines of this?)
```
$ task --list
test         task test_unit
test_unit    pytest {unit_test_dir} -v --cov {src_dir} --cov-report term-missing

Variables:
  {src_dir}        src
  {unit_test_dir}  tests/unit
```

I would imagine if we do this, it would only make sense to show the final "Variables" section if it is either globally enabled or at least one task is using it (via the inline use_vars)?

The more I thought about it, the more I felt this approach is the most consistent with the current behavior. Why? Because it's not like we resolve the `task test_unit` into the full command either. The reason that is fine is because `test_unit` is in the list of tasks we're listing out so we can see what that value of `test_unit` is if we're curious what that included task command is doing.

However, that isn't the case with the variables. If we're using any variables, recursive or not, we don't know what their values are with regards to the current task list output unless we went to go look at the `pyproject.toml` file, which kinda defeats the purpose of using the `--list` flag in the first place.

**Comment by illBeRoy** [comment]
I like the proposal! Let's do that.

I have but one addition:

Let's emphasize the variables inside the tasks using colorama (same as we do with task names, but using a different color). We can do that to indicate which tasks have variables available, that is, for:

```toml
[tool.taskipy.variables]
path = "path/to/{dir}"
dir = "my_module"

[tool.taskipy.tasks]
lint = { cmd = "pylint {path}", use_vars = true }
black = { cmd = "black {path}", use_vars = false }
```

We'll get:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/6681893/187546538-8b7d250d-358e-4cce-bb95-784bd2fcbc02.png">

(The variable in `lint` task is in cyan since it's really a variable. The one in `black` is not highlighted, since this task does not use vars and therefore is interpreted literally)
